AWSTemplateFormatVersion: '2010-09-09'
Resources:
  MustafPublicEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      SecurityGroups:
        - !Ref EC2InstancePublicSecurityGroup
      KeyName: ec201
      ImageId: ami-0e1b7f1022bdcd0c4
      InstanceType: t2.micro
      Tags: 
        - Key: username
          Value: mustaf

  EC2InstancePublicSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0
  
  MustafPrivateEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      SecurityGroups:
        - !Ref EC2InstancePrivateSecurityGroup
      KeyName: ec201
      ImageId: ami-0e1b7f1022bdcd0c4
      InstanceType: t2.micro
      Tags: 
        - Key: username
          Value: mustaf

  EC2InstancePrivateSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 172.31.0.0/16
Outputs:
  PublicIpOfPublicEC2Instance:
    Description: The MustafPublicEC2Instance ID
    Value: !GetAtt MustafPublicEC2Instance.PublicIp
  
  PublicIpOfPrivateEC2Instance:
    Description: The MustafPrivateEC2Instance ID
    Value: !GetAtt MustafPrivateEC2Instance.PublicIp