AWSTemplateFormatVersion: '2010-09-09'
Description: Tamplate for creatig a EC2 instance in a specific Subnet of Defult subnet

Parameters:
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Key Pair name
    Default: ec201
  EC2ImageId:
    Type: AWS::EC2::Image::Id
    Description: Image where EC2 will lonch (its a linux image)
    Default: ami-0e1b7f1022bdcd0c4
  VpcId:
    Description: Vpc ID
    Type: AWS::EC2::VPC::Id
    Default: vpc-b7cadbcf
  SubnetId: 
    Type: AWS::EC2::Subnet::Id
    Description: Perticular Subnet in Default VPC
    Default: subnet-255ea12a
  EC2InstanceType:
    Type: String
    Description: EC2 Instance Type
    Default: t2.micro
  Creator:
    Type: String
    Description: Name of the stack creator
    Default: ''
  Project: 
    Type: String
    Description: Name of the Project
    Default: "AWS-Subnet-Lession"
  Environment:
    Type: String
    Description: Project Environment
    Default: Dev
    
Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      SecurityGroupIds: 
        - !GetAtt SecurityGroupEnableSSH.GroupId
      KeyName: !Ref KeyName
      ImageId: !Ref EC2ImageId
      SubnetId: !Ref SubnetId
      InstanceType: !Ref EC2InstanceType
      Tags: 
        - Key: username
          Value: !Ref Creator

  SecurityGroupEnableSSH: 
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref VpcId
      GroupName: !Sub ${Project}-ec2-sg-${Environment}
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0
      Tags: 
        - Key: username
          Value: !Ref Creator
  
 
Outputs:
  EC2Instance:
    Description: The EC2Instance ID
    Value: !GetAtt EC2Instance.PublicIp